server:
  port: 8082

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/patient/**

        - id: notes-services
          uri: http://localhost:8083
          predicates:
            - Path=/note/**

        - id: risque-services
          uri: http://localhost:8084
          predicates:
            - Path=/risque/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT


# Pour la gestion des logs et la surveillance
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
